### ISSUE TITLE
"The account appears to be private and cannot be viewed by the bot."

### ISSUE THREAD

**Issue by Twooearly** [bman46/InstagramEmbedDiscordBot#70]
I understand what the Bot is telling me, but why can't I subscribe to a private account, when I can view the posts of the exact same private Account?
I just would love to understand this.
Thank you in advantage!

**Comment by bman46** [comment]
I check if the account is private with the data sent back from IG. This is for a variety of reasons:
1. Should there be multiple bot accounts used with the bot, it is more consistent
2. To avoid intruding on the privacy of others (their account is private, so they don't want it shared to everyone)
While you could change this on your own, I dont condone it and won't provide any support for changing it due to the aforementioned reasons.

**Comment by Twooearly** [comment]
Okay that I can understand, thank you very much for your explanation and your response!
